from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.user_login, name='login'),
    path('forgot-password/', views.forgot_password, name='forgot_password'), 
    path('create-account/', views.create_account, name='create_account'), 
    path('logout/', views.user_logout, name='logout'),
    path('api/submit/expense/', views.submit_expense, name='submit_expense'),
    path('api/submit/income/', views.submit_income, name='submit_income'),
    path('api/submit/add_bank_account/', views.add_bank_account, name='add_bank_account'),
    path('api/list/expenses/', views.list_expenses, name='list_expenses'),
    path('api/list/incomes/', views.list_incomes, name='list_incomes'),
    path('api/update/expense/<int:expense_id>/', views.update_expense, name='update_expense'),
    path('api/update/income/<int:income_id>/', views.update_income, name='update_income'),
    path('api/update/edit_bank_account/', views.edit_bank_account, name='edit_bank_account'),
    path('api/delete/expense/<int:expense_id>/', views.delete_expense, name='delete_expense'),
    path('api/delete/income/<int:income_id>/', views.delete_income, name='delete_income'),
    path('api/submit/income_category/', views.submit_income_category, name='submit_income_category'),
    path('api/submit/expense_category/', views.submit_expense_category, name='submit_expense_category'),
    path('api/list/income_categories/', views.list_income_categories, name='list_income_categories'),
    path('api/list/expense_categories/', views.list_expense_categories, name='list_expense_categories'),
    path('api/list_bank_accounts/', views.list_bank_accounts, name='list_bank_accounts'),
    path('api/update/token/<int:token_id>/', views.update_token, name='update_token'),
    path('api/update/bank_account/<int:account_id>/', views.update_bank_account, name='update_bank_account'),
    path('api/update/monthly_expense/<int:expense_id>/', views.update_monthly_expense, name='update_monthly_expense'),
    path('api/delete/income_category/<int:category_id>/', views.delete_income_category, name='delete_income_category'),
    path('api/delete/expense_category/<int:category_id>/', views.delete_expense_category, name='delete_expense_category'),
    path('api/delete/token/<int:token_id>/', views.delete_token, name='delete_token'),
    path('api/delete/bank_account/<int:account_id>/', views.delete_bank_account, name='delete_bank_account'),
    path('api/delete/monthly_expense/<int:expense_id>/', views.delete_monthly_expense, name='delete_monthly_expense'),
    path('reset_password/<str:uidb64>/<str:token>/', views.reset_password, name='reset_password'),
]